### ISSUE TITLE
Requirements Milestone 2 part a

### ISSUE THREAD

**Issue by corysabol** [sible777/Concordanator#1]
Comment any questions about each req here that you may have asked that need an answer or questions that you asked but found the answer to.
- For each req a list of questions that
  1. That need an answer
  2. That you have asked, and the answer you have found
- A graph or table of dependencies
- How will we test the requirements
- Implications of the requirement for implementation

Of course this can all be read in the document provided by Oldham.

**Comment by corysabol** [comment]
Does the command line interface need to be a standalone window that opens then launched? I can write a class for this. Or maybe @askewseth can work on that?

**Comment by askewseth** [comment]
How do we determine line number? Do we include the beginning (header)? Do
we include blank lines?  Do we index by page number or only by raw line
number, ex) page 57 line 30 vs line 3,692

Do we need to deal with things like hyphenated words? ex) self-worth =?
self worth

I'm assuming that we need to ignore cases, but it was never explicitly
mentioned so just in case.

What makes something a common word?  Are we supposed to make a list of
common words such as articles and filter those out or are we supposed to
allow the user to define words they don't care about?

**Comment by askewseth** [comment]
Yeah I can work on the CLI if y'all want me to.  But if I'm not mistaken the CLI is really just a wrapper for all of the other classes, just making them callable from the command line, and if that's the case then I wouldn't really be able to accomplish much on it until I had the rest of the program to call.

**Comment by corysabol** [comment]
@askewseth Those are some really great questions! I would assume that we can simply let user search for a hyphenated word and only return that exact string. We can use regex to math a little better, but that's a bit of a hassle. 

As for the cli, yeah I think that's just a wrapper. Once we have the shell up and such then you can just include the empty classes you would depend on for full functionality.

You can break it down into features and work on the ones that can stand by themselves. Like parsing the command line args into tokens and such.

**Comment by corysabol** [comment]
Closing issue
