### ISSUE TITLE
Program Crashes when building con

### ISSUE THREAD

**Issue by corysabol** [sible777/Concordanator#26]
### branch: CmdRepl

``` java
> build Peter Pan
Building the concordance. This may take a moment for large books.
|=======  | Stage 7 of 9Exception in thread "main" java.lang.NullPointerException
    at java.io.FileInputStream.<init>(FileInputStream.java:130)
    at java.io.FileReader.<init>(FileReader.java:72)
    at ClassLibrary.Concord.set_common_words(Concord.java:403)
    at ClassLibrary.Concord.<init>(Concord.java:54)
    at ClassLibrary.CmdRepl.buildConcordance(CmdRepl.java:440)
    at ClassLibrary.CmdRepl.evalCmd(CmdRepl.java:205)
    at ClassLibrary.CmdRepl.startRepl(CmdRepl.java:127)
    at Concordanator.main(Concordanator.java:23)
```

I'm not sure why this is happening, could @Metalaxe1 or @askewseth try to reproduce this?

I will dig into the stack track tomorrow, it's rather late now.

**Comment by askewseth** [comment]
I just tried it using Peter Pan and it worked fine for me.  It's throwing an error in the set_common_words part, and its a null pointer for the file reader, so I'm guessing that it isn't able to find 'commonwords.txt' for some reason.

**Comment by corysabol** [comment]
Cool, thanks man. Can you continue to test around and use the program. I have to some more coding shortly to implement some summary commands and such. As well as handle large output to the screen.

**Comment by askewseth** [comment]
Yeah sure, I'm going through and fixing everything in concord.java right now.

**Comment by corysabol** [comment]
Alright. I've added a method to Concord in my CmdRepl branch which will help with generating summaries, so tonight or some time tomorrow we can do a big merge and get it submission ready.

**Comment by corysabol** [comment]
@askewseth Correct, on not being able to find commonwords.txt

*nix build script now copies over critical files to the build folder.

FIXED
