### ISSUE TITLE
Bookshelf should accept query for book

### ISSUE THREAD

**Issue by corysabol** [sible777/Concordanator#6]
And return the correct book instance.

**Comment by Metalaxe1** [comment]
My branch now contains the "getBookTitlesByKeyword" which accepts a string parameter.  The keyword is not case sensitive.  Cities = cities

**Comment by corysabol** [comment]
Yeah, I looked at it. I am just making these feature issues as we go, so that we can close them and track completion of milestones with nice graphs :+1: 

I will close it now.
